### PR TITLE
Rewrite core for reliability & efficiency

### PR DESCRIPTION
**Pull request by VirxEC**
- Exclusively use channels to communicate between threads
- Using `TCPMessenger` to send/get messages to/from Rocket League is handled on its own thread
- Async is used to read incoming messages from channels and the network at the same time
- `gamePort` is automatically selected upon launch
  - This means passing in the port via the command line is no longer needed/supported
  - Search behavior has changed from how v4 finds the port - v4 used to use the first open port it could find but we now:
    - Search for an open instance of Rocket League and try to read the port
    - Default to searching for an open port, but skip the port used for the sockets api
    - This new process fixes many errors that could happen in v4
- Listen for connections on `0.0.0.0` instead of only `127.0.0.1` so RLBot will listen to every address as long as it's got the correct port of the sockets API
  - This feature will makes remote rlbots connecting to a central "server" easier
- Make rumble default to `No_Rumble` upon there not being a key found
- Move `rlbot.flat` back into core from bridge
- Updated info in the README

### CODE REVIEW

**Comment by swz-git** [comment]
I'm assuming `gamePort` is the port that core connects to RL with. What about the port that bots connect to? Is it still 23234 by default?

**Comment by VirxEC** [comment]
Yes

**Comment by VirxEC** [comment]
I converted this to a draft due to the relevant bridge PRs not being pulled yet - once this is done, the updated DLL will be added here, allowing this branch to compile. The PR will then be marked as ready for review again.

**Review by NicEastvillage — APPROVED** [review]
LGTM

**Review by TangilJ — APPROVED** [review]

**Pull request merged**
